#!/bin/sh

################################################################################
#      This file is part of LibreELEC - https://LibreELEC.tv
#      Copyright (C) 2016 Team LibreELEC
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

echo "Generating uImage..."

$TOOLCHAIN/bin/mkimage -A arm64 -O linux -T kernel -C none -a 0x1080000 -e 0x1080000 -n Linux -d $TARGET_IMG/$IMAGE_NAME.kernel $TARGET_IMG/$IMAGE_NAME.uImage
mv $TARGET_IMG/$IMAGE_NAME.uImage $TARGET_IMG/$IMAGE_NAME.kernel

[ -e $BOOTLOADER_DIR/release ] && . $BOOTLOADER_DIR/release
