#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2017-present Team LibreELEC (https://libreelec.tv)

mkdir -p $RELEASE_DIR/3rdparty/bootloader
  cp -a $(get_build_dir linux)/arch/$TARGET_KERNEL_ARCH/boot/dtb.img $RELEASE_DIR/3rdparty/bootloader
  cp -a $(get_build_dir aml_autoscript)/* $RELEASE_DIR/3rdparty/bootloader
