#!/bin/sh

display_mode=$(cat /sys/class/display/mode)

if [ -z "$display_mode" ]; then
    display_mode="720p"
fi

# Parse command line arguments
for arg in $(cat /proc/cmdline); do
  case $arg in
    hdmitx=*)
      hdmitx="${arg#*=}"
      ;;
    hdmimode=*)
      display_mode="${arg#*=}"
      ;;
    BOOT_IMAGE=*)
      BOOT_IMAGE="${arg#*=}"
      ;;
    boot=*)
      boot="${arg#*=}"
      ;;
    disk=*)
      disk="${arg#*=}"
      ;;
  esac
done

# Enable HDMI output if cable is connected and not already enabled by u-boot
#if [ "$(cat /sys/class/amhdmitx/amhdmitx0/hpd_state)" != "0" ] && [ "$display_mode" != "$hdmimode" ]; then
#  display_mode="$hdmimode"
#fi

# Add information where to run LibreELEC from
if [ -z "$BOOT_IMAGE" -o -z "$boot" -o -z "$disk" ]; then
  cmdline=$(cat /proc/cmdline)
  cmdline="$cmdline BOOT_IMAGE=/dev/boot boot=/dev/system disk=/dev/data"
  echo "$cmdline" > /proc/cmdline
fi

# Force enable CEC if configuration parameter not present or empty
if [ -z "$hdmitx" ]; then
  echo 0xf > /sys/class/amhdmitx/amhdmitx0/cec_config
fi

# Set framebuffer geometry to match the resolution
case $display_mode in
  480*)            X=720  Y=480  ;;
  576*)            X=720  Y=576  ;;
  720p*)           X=1280 Y=720  ;;
  *)               X=1920 Y=1080 ;;
esac

fbset -fb /dev/fb0 -g $X $Y 1920 2160 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo $display_mode > /sys/class/display/mode
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank

# Blank fb1 to prevent static noise
echo 1 > /sys/class/graphics/fb1/blank

for part in /sys/block/*/queue/add_random; do
  echo 0 > "$part"
done

echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
